# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0002_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('accountid', models.CharField(max_length=30)),
                ('accesskey', models.CharField(max_length=30)),
                ('secretkey', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Credentials',
            },
        ),
    ]
