# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0004_auto_20170903_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='accountid',
        ),
        migrations.AlterField(
            model_name='credentials',
            name='accesskey',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='secretkey',
            field=models.CharField(max_length=200),
        ),
    ]
