# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0005_auto_20170903_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='secretkey',
        ),
        migrations.AddField(
            model_name='credentials',
            name='accountid',
            field=models.CharField(default=123456789876, max_length=200),
            preserve_default=False,
        ),
    ]
