# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0007_credentials_secretkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='secretkey',
            new_name='skey',
        ),
    ]
