# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0008_auto_20170904_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='skey',
        ),
    ]
